# Generated by Django 5.2.9 on 2025-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/'),
        ),
    ]
